"""Parse a Westlaw UK case ``.rtf`` export into everything the importer needs.

Westlaw's "print/download" RTF is a very different animal from the BAILII ``.rtf``
that :mod:`raglex.formats.rtf` handles. It is machine-generated by the *Apache XML
Graphics RTF Library* and is dense with chrome the plain-text strip in ``formats.rtf``
was never meant to survive:

  * a running **header** (``{\\header …}``) that repeats the case name + Westlaw
    citation on every page, and a **footer** with the Thomson Reuters copyright and a
    ``\\chpgn`` page number;
  * embedded **PNG images** — the "Positive/Neutral Judicial Consideration" status
    flags — carried as ``{\\*\\shppict{\\pict …}}`` hex blobs;
  * **hyperlink fields** (``{\\field{\\*\\fldinst HYPERLINK "…"}{\\fldrslt …}}``)
    wrapping every report citation, statute and judge name;
  * curly quotes/dashes as RTF *control words* (``\\rquote``, ``\\ldblquote``,
    ``\\endash``) rather than ``\\'xx`` bytes — the regex strip deletes them **with the
    surrounding space**, so "investors' funds" becomes "investorsfunds".

So this module carries its own brace-aware, destination-skipping RTF tokenizer
(:func:`rtf_to_text`) that discards image/field/table destinations, keeps ``\\fldrslt``
display text, and maps the punctuation control words to real characters.

On top of the clean text sits a small structural parser (:func:`parse_westlaw_rtf`).
Westlaw lays the front matter out as blank-line-delimited *label → value* blocks
(``Court`` / ``Judgment Date`` / ``Where Reported`` / ``Report Citation`` / ``Subject`` /
``Keywords`` / ``Judge`` / ``Counsel`` / ``Solicitor`` / ``Case Digest`` …), the same in
both surfaces the corpus meets:

  * the **Case Analysis** digest (a ``Where Reported`` list of parallel citations, an
    editorial ``Abstract`` / ``Held``); and
  * a reproduced **Law Report** (a single ``Report Citation``, ICLR catchwords, a
    headnote, ``*149`` star-pages, a ``Representation`` block, footnoted authorities).

Both open with the same running-header line — ``{name}, {citation} ({year})`` — whose
citation is Westlaw's *preferred* one (an ICLR report for older cases, a ``NNNN WL
NNNNNN`` document id for the rest). Every parallel citation, the neutral citation, the
ECLI (EU cases reported in UK series) and the WL id are surfaced so the importer can key
the case by its strongest identity and mint the rest as aliases.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date

from ..core.models import Segment
from .bailii_corpus import clean_case_name

# ── RTF tokenizer ────────────────────────────────────────────────────────────

# Groups whose *content* is chrome, not text: font/colour/style tables, the
# generator/info blocks, images (pict/shppict) and the instruction half of a field
# (the raw ``HYPERLINK "url"``) — the visible ``\fldrslt`` half sits in a sibling group
# and is kept. Marking the group as a skipped destination drops everything inside it.
_DESTINATIONS = frozenset({
    "fonttbl", "filetbl", "colortbl", "stylesheet", "listtable",
    "listoverridetable", "revtbl", "rsidtbl", "generator", "info", "pict",
    "object", "objdata", "themedata", "colorschememapping", "latentstyles",
    "datastore", "wgrffmtfilter", "xmlnstbl", "fldinst", "pgptbl", "ftnsep",
    "ftnsepc", "aftnsep", "aftnsepc", "bkmkstart", "bkmkend", "shppict",
    "nonshppict", "panose", "falt", "shpinst", "do", "company", "operator",
    "template", "subject", "keywords", "author", "title",
})
# Control words that *are* content — structural whitespace and the punctuation Westlaw
# encodes as control words rather than bytes.
_CTRL_CHARS = {
    "par": "\n", "line": "\n", "cell": "\n", "row": "\n", "sect": "\n",
    "page": "\n", "tab": "\t", "emdash": "—", "endash": "–",
    "emspace": " ", "enspace": " ", "qmspace": " ", "bullet": "•",
    "lquote": "‘", "rquote": "’", "ldblquote": "“",
    "rdblquote": "”", "nbsp": " ",
}


def rtf_to_text(data: bytes) -> str:
    """Reduce a Westlaw RTF byte string to clean Unicode text (pure).

    A single left-to-right pass over the RTF with a group stack:

      * ``{`` / ``}`` push/pop a group; a group inherits its parent's *skip* flag and
        ``\\ucN`` unicode-fallback count;
      * a destination control word (or a ``\\*`` ignorable marker) flips the current
        group to *skipped* — its text, and any nested groups, are discarded;
      * ``\\uN`` emits the code point then skips the next ``uc`` fallback chars (the
        ``\\'3f`` "?" Westlaw pairs with every non-CP1252 glyph);
      * ``\\'xx`` decodes one CP1252 byte; the punctuation control words map via
        :data:`_CTRL_CHARS`; every other control word is formatting and dropped.
    """
    s = data.decode("latin-1")
    out: list[str] = []
    i, n = 0, len(s)
    stack: list[list] = [[False, 1]]  # each frame: [skip_destination, uc]
    uskip = 0  # unicode-fallback chars still to swallow after a \uN
    while i < n:
        c = s[i]
        if c == "{":
            top = stack[-1]
            stack.append([top[0], top[1]])
            i += 1
        elif c == "}":
            if len(stack) > 1:
                stack.pop()
            i += 1
        elif c == "\\":
            j = i + 1
            if j < n and s[j].isalpha():
                k = j
                while k < n and s[k].isalpha():
                    k += 1
                word = s[j:k]
                p = k
                neg = p < n and s[p] == "-"
                if neg:
                    p += 1
                num = ""
                while p < n and s[p].isdigit():
                    num += s[p]
                    p += 1
                param = (int(num) * (-1 if neg else 1)) if num else None
                if p < n and s[p] == " ":  # a single space delimits the control word
                    p += 1
                i = p
                if word in _DESTINATIONS:
                    stack[-1][0] = True
                elif word == "uc":
                    stack[-1][1] = param if param is not None else 1
                elif word == "u":
                    if not stack[-1][0]:
                        cp = param if param is not None else 0
                        if cp < 0:
                            cp += 65536
                        try:
                            out.append(chr(cp))
                        except ValueError:
                            pass
                    uskip = stack[-1][1]
                elif not stack[-1][0] and word in _CTRL_CHARS:
                    out.append(_CTRL_CHARS[word])
            else:
                sym = s[j] if j < n else ""
                if sym == "'":
                    hx = s[j + 1:j + 3]
                    i = j + 3
                    if uskip > 0:
                        uskip -= 1
                    elif not stack[-1][0]:
                        try:
                            out.append(bytes([int(hx, 16)]).decode("cp1252"))
                        except (ValueError, UnicodeDecodeError):
                            pass
                    continue
                i = j + 1
                if stack[-1][0]:
                    continue
                if sym == "~":
                    out.append(" ")
                elif sym == "_":
                    out.append("-")
                elif sym in ("{", "}", "\\"):
                    out.append(sym)
                elif sym == "*":
                    stack[-1][0] = True
                elif sym in ("\n", "\r"):
                    out.append("\n")
        elif c in "\r\n":
            i += 1  # raw line breaks in the RTF source are wrapping, not content
        else:
            if uskip > 0:
                uskip -= 1
            elif not stack[-1][0]:
                out.append(c)
            i += 1
    return "".join(out)


def _tidy(text: str) -> str:
    """Collapse the tokenizer's whitespace: trailing spaces, runs of spaces/tabs, and
    3+ blank lines down to a single blank line (the block separator we parse on)."""
    text = "\n".join(ln.strip() for ln in text.split("\n"))
    text = re.sub(r"[ \t ]{2,}", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


# ── structural parse ─────────────────────────────────────────────────────────

# The label lines Westlaw uses for its front-matter blocks. Order-insensitive; a block
# is a label line followed by its value lines up to the next blank line.
_META_LABELS = {
    "court", "judgment date", "where reported", "report citation", "subject",
    "other related subjects", "keywords", "judge", "counsel", "solicitor",
    "representation", "appearances", "case digest", "abstract", "summary",
}
# Report-citation-ish value line: opens with a year in brackets/parens, or a bare
# ``64 Con. L.R. 1`` reporter, or an ECLI, or a newspaper report. Deliberately loose —
# the blank-line block boundary already fences the citation list, so this only has to
# reject the odd label that slipped through.
_REPORTISH = re.compile(
    r"^(\[\d{4}\]|\(\d{4}\)|\d{1,4}\s+[A-Z]|ECLI:|EU:[CTF]:|Times[,\s]|"
    r"Independent[,\s]|Guardian[,\s]|Daily Telegraph[,\s])", re.IGNORECASE)
# A neutral citation among the report list (post-2001 UK, plus the devolved/Irish
# equivalents). WLUK ("[1999] 2 WLUK 258") is Westlaw's own pseudo-neutral — NOT one.
_NEUTRAL_COURTS = (
    r"UKSC|UKHL|UKPC|EWCA|EWHC|EWCOP|EWFC|UKUT|UKFTT|UKEAT|EAT|"
    r"CSOH|CSIH|SC|HCJ|NICA|NIQB|NICh|IESC|IECA|IEHC|UKAITUR|UKIAT")
_NEUTRAL = re.compile(rf"\[(\d{{4}})\]\s*({_NEUTRAL_COURTS})\b", re.IGNORECASE)
# The whole neutral citation, including a court sub-designator ("EWCA Civ") and a
# trailing division in parentheses ("[2016] EWHC 2581 (Admin)") — for lifting the
# neutral out of a transcript's dateline when Westlaw prints no "Where Reported" list.
_NEUTRAL_FULL = re.compile(
    rf"\[\d{{4}}\]\s*(?:{_NEUTRAL_COURTS})(?:\s+[A-Z][a-z]+)?\s+\d+"
    r"(?:\s*\([A-Za-z]+\))?", re.IGNORECASE)
_WLUK = re.compile(r"\bWLUK\b")
# The Westlaw document id in the running header: "… , 1999 WL 250101 (1999)".
_WL_NUMBER = re.compile(r"\b(\d{4})\s+WL\s+(\d+)\b")
# ECLI in ``Where Reported`` — Westlaw drops the "ECLI:" prefix ("EU:C:2016:198").
_ECLI = re.compile(r"\b(ECLI:)?(EU:[CTF]:\d{4}:\d+)\b")
# A CJEU case number carried in the party line: "Aranyosi (C-404/15 PPU)".
_CASE_NO = re.compile(r"\b([CT]-\d+/\d+)\b")
# The running-header line that opens every export: "{name}, {citation} ({year})".
_HEADER_LINE = re.compile(r"^(.*?),\s*([^,]*?)\s*\((\d{4})\)\s*$")
# A star-page pin (ICLR pagination): "*149" at a line start or mid-run.
_STAR_PAGE = re.compile(r"\*(\d{1,4})\b")
# A numbered judgment paragraph heading a line: "42. The appellant …".
_PARA_LINE = re.compile(r"^(\d{1,3})\.\s+\S")
# Boilerplate lines to drop from the body.
_BOILERPLATE = re.compile(
    r"^(©|\(c\))\s*\d{4}\s+Thomson Reuters", re.IGNORECASE)
_MONTHS = {m: i for i, m in enumerate(
    ["january", "february", "march", "april", "may", "june", "july", "august",
     "september", "october", "november", "december"], start=1)}
# Court-label → canonical short code, so a Westlaw case sits in the same court buckets
# as its harvested neighbours. Order matters (first substring hit wins); anything
# unmatched keeps the descriptive label in meta and leaves ``court`` unset.
_COURT_CODES = (
    ("supreme court", "uksc"),
    ("house of lords", "ukhl"),
    ("privy council", "ukpc"),
    ("court of appeal", "ewca"),
    ("employment appeal", "ukeat"),
    ("upper tribunal", "ukut"),
    ("chancery division", "ewhc"),
    ("queen's bench", "ewhc"),
    ("queens bench", "ewhc"),
    ("king's bench", "ewhc"),
    ("kings bench", "ewhc"),
    ("family division", "ewhc"),
    ("administrative court", "ewhc"),
    ("high court of justice", "ewhc"),
    ("court of justice", "cjeu"),
    ("general court", "cjeu"),
    ("court of first instance", "cjeu"),
    ("human rights", "echr"),
    ("court of session", "csoh"),
)


@dataclass(slots=True)
class ParsedWestlaw:
    """One Westlaw RTF export, reduced to the fields the importer stores."""

    title: str | None                      # the header running-title (short party form)
    text: str = ""                         # substantive body (front matter → judgment)
    segments: list[Segment] = field(default_factory=list)
    report_citations: tuple[str, ...] = ()  # every parallel citation (aliases)
    neutral_citation: str | None = None    # e.g. "[2005] UKPC 37" (identity, if any)
    ecli: str | None = None                # normalised "ECLI:EU:C:2016:198" (EU cases)
    case_number: str | None = None         # CJEU docket, e.g. "C-404/15"
    wl_number: str | None = None           # Westlaw id, e.g. "1999 WL 250101"
    court_code: str | None = None          # canonical short code, when recognised
    court_label: str | None = None         # the descriptive court, as printed
    decision_date: date | None = None
    judges: tuple[str, ...] = ()
    counsel: tuple[str, ...] = ()
    solicitors: tuple[str, ...] = ()
    subjects: tuple[str, ...] = ()
    keywords: tuple[str, ...] = ()
    party_full: str | None = None          # the full (multi-)party heading
    also_known_as: tuple[str, ...] = ()
    is_eu: bool = False


def _parse_date(value: str) -> date | None:
    m = re.search(r"(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})", value or "")
    if not m:
        return None
    mon = _MONTHS.get(m.group(2).lower())
    if not mon:
        return None
    try:
        return date(int(m.group(3)), mon, int(m.group(1)))
    except ValueError:
        return None


def _blocks(text: str) -> list[list[str]]:
    """Split the tidied text into blank-line-delimited blocks of non-empty lines."""
    out: list[list[str]] = []
    cur: list[str] = []
    for ln in text.split("\n"):
        if ln.strip():
            cur.append(ln.strip())
        elif cur:
            out.append(cur)
            cur = []
    if cur:
        out.append(cur)
    return out


def _court_code(label: str | None) -> str | None:
    # normalise curly apostrophes away so "Queen's" matches the apostrophe-free needles
    low = (label or "").lower().replace("’", "").replace("'", "")
    for needle, code in _COURT_CODES:
        if needle.replace("'", "") in low:
            return code
    return None


def _star_segments(text: str) -> list[Segment]:
    """Star-page pins ("*149") as page segments — the pinpoint unit of a reproduced
    ICLR/AC report ("[1982] 1 WLR 149, 152"). Trusted only when several appear in
    non-decreasing order, so a stray "*1" footnote marker can't fake pagination."""
    marks: list[tuple[int, int]] = []
    for m in _STAR_PAGE.finditer(text):
        marks.append((int(m.group(1)), m.start()))
    kept = [
        (pg, at) for i, (pg, at) in enumerate(marks)
        if i == 0 or pg >= marks[i - 1][0]
    ]
    # de-duplicate consecutive repeats of the same page
    dedup: list[tuple[int, int]] = []
    for pg, at in kept:
        if not dedup or dedup[-1][0] != pg:
            dedup.append((pg, at))
    if len(dedup) < 3:
        return []
    segs: list[Segment] = []
    for i, (pg, at) in enumerate(dedup):
        end = dedup[i + 1][1] if i + 1 < len(dedup) else len(text)
        segs.append(Segment(label=f"*{pg}", char_start=at, char_end=end, kind="page"))
    return segs


def _para_segments(text: str) -> list[Segment]:
    """Numbered-paragraph segments from an ascending "N. " numbering (modern
    transcripts). Same seam-detection as the BAILII importer: several paragraphs,
    each strictly greater than both neighbours, so stray "3." prose can't fake it."""
    marks: list[tuple[int, int]] = []
    offset = 0
    for block in text.split("\n"):
        m = _PARA_LINE.match(block)
        if m:
            marks.append((int(m.group(1)), offset))
        offset += len(block) + 1
    ascending = [
        (num, at) for i, (num, at) in enumerate(marks)
        if (i == 0 or num > marks[i - 1][0])
        and (i + 1 == len(marks) or num < marks[i + 1][0])
    ]
    if len(ascending) < 3:
        return []
    segs: list[Segment] = []
    for i, (num, at) in enumerate(ascending):
        end = ascending[i + 1][1] if i + 1 < len(ascending) else len(text)
        segs.append(Segment(label=f"para {num}", char_start=at, char_end=end, kind="paragraph"))
    return segs


def parse_westlaw_rtf(data: bytes, *, filename: str | None = None) -> ParsedWestlaw | None:
    """Parse one Westlaw ``.rtf`` export. Returns None only when the bytes aren't a
    recognisable Westlaw export (no ``\\rtf`` signature, or nothing that reads like the
    running-header citation line)."""
    if not data[:6].lstrip().startswith(b"{\\rtf"):
        return None
    text = _tidy(rtf_to_text(data))
    if not text:
        return None

    lines = text.split("\n")
    # 1) running-header line → short title + preferred citation + year
    header_title = header_cite = None
    header_year: int | None = None
    hm = _HEADER_LINE.match(lines[0]) if lines else None
    if hm:
        header_title, header_cite, header_year = hm.group(1).strip(), hm.group(2).strip(), int(hm.group(3))

    # 2) drop the running header + copyright/"for educational use only" boilerplate so
    #    the body starts at the full party heading.
    body_lines: list[str] = []
    for idx, ln in enumerate(lines):
        low = ln.lower()
        if idx == 0 and hm:
            continue
        if _BOILERPLATE.match(ln) or low == "for educational use only":
            continue
        body_lines.append(ln)
    body = re.sub(r"\n{3,}", "\n\n", "\n".join(body_lines)).strip()

    blocks = _blocks(body)

    # 3) walk the front-matter blocks, filling recognised label → value fields. The
    #    party heading is the block(s) before the first recognised label — Westlaw's
    #    status flag ("… Judicial Consideration" / "No Substantial Judicial Treatment")
    #    and "Also known as:" lines are lifted out of it. Once a label is seen, only
    #    label blocks contribute fields; the headnote/judgment prose in between is body.
    fields: dict[str, list[str]] = {}
    party_lines: list[str] = []
    aka: list[str] = []
    in_meta = False
    for blk in blocks:
        head = blk[0].lower().rstrip(":")
        if head in _META_LABELS:
            in_meta = True
            # "Case Digest" heads a sub-labelled block (Abstract/Summary/Held …); its
            # own label line is dropped, the values follow.
            fields.setdefault(head, []).extend(blk[1:])
            continue
        if in_meta:
            continue  # headnote / judgment prose between labels — kept in body, not fields
        for ln in blk:
            low = ln.lower()
            if low.startswith("also known as"):
                aka.append(re.sub(r"^also known as:\s*", "", ln, flags=re.IGNORECASE))
            elif re.search(r"judicial (consideration|treatment)$", low):
                pass  # the status flag — neither party nor field
            else:
                party_lines.append(ln)

    # citations: the two citation labels + the header preferred citation
    cite_lines: list[str] = []
    for lab in ("where reported", "report citation"):
        cite_lines += fields.get(lab, [])
    report_cites: list[str] = []
    seen: set[str] = set()
    for c in ([header_cite] if header_cite else []) + cite_lines:
        c = c.strip()
        if not c or not _REPORTISH.match(c):
            continue
        # keep only up to the URL-stripped citation (defensive) and de-dupe
        key = c.lower()
        if key not in seen:
            seen.add(key)
            report_cites.append(c)

    neutral = None
    for c in report_cites:
        if _NEUTRAL.search(c) and not _WLUK.search(c):
            neutral = _NEUTRAL_FULL.search(c).group(0) if _NEUTRAL_FULL.search(c) else c
            break
    # Transcript-layout exports (a modern judgment, no "Where Reported" list) carry the
    # neutral citation in the dateline instead: "… [2016] EWHC 2581 (Admin), 2016 WL …".
    if neutral is None:
        bm = _NEUTRAL_FULL.search(body[:2500])
        if bm:
            neutral = bm.group(0)
            if neutral.lower() not in seen:
                report_cites.insert(0, neutral)

    ecli = None
    for c in report_cites + party_lines + [header_cite or ""]:
        em = _ECLI.search(c)
        if em:
            ecli = "ECLI:" + em.group(2)
            break

    wl_number = None
    for src in ([header_cite] if header_cite else []) + [lines[0] if lines else ""]:
        wm = _WL_NUMBER.search(src or "")
        if wm:
            wl_number = f"{wm.group(1)} WL {wm.group(2)}"
            break

    case_no = None
    for ln in party_lines + ([header_title or ""]):
        cm = _CASE_NO.search(ln)
        if cm:
            case_no = cm.group(1)
            break

    court_label = " ".join(fields.get("court", [])) or None
    decision_date = _parse_date(" ".join(fields.get("judgment date", [])))
    if decision_date is None and header_year:
        decision_date = None  # year alone isn't a date; header_year still keys aliases

    subjects = tuple(dict.fromkeys(
        s.strip() for lab in ("subject", "other related subjects")
        for raw in fields.get(lab, []) for s in raw.split(";") if s.strip()))
    keywords = tuple(dict.fromkeys(
        k.strip() for raw in fields.get("keywords", []) for k in raw.split(";") if k.strip()))

    judges = tuple(dict.fromkeys(j for j in fields.get("judge", []) if j))
    counsel = tuple(fields.get("counsel", []) or fields.get("representation", []))
    solicitors = tuple(fields.get("solicitor", []))

    party_full = " ".join(party_lines).strip() or None
    title_raw = header_title or (party_lines[0] if party_lines else None)
    # strip a leading "*149 " star-page from a law-report party heading
    if title_raw:
        title_raw = re.sub(r"^\*\d+\s+", "", title_raw).strip()
    clean = clean_case_name(title_raw)
    title = clean.title or title_raw or None

    is_eu = bool(ecli) or _court_code(court_label) == "cjeu"

    segments = _para_segments(body) or _star_segments(body)

    return ParsedWestlaw(
        title=title,
        text=body,
        segments=segments,
        report_citations=tuple(report_cites),
        neutral_citation=neutral,
        ecli=ecli,
        case_number=case_no,
        wl_number=wl_number,
        court_code=court_from_label(court_label, neutral),
        court_label=court_label,
        decision_date=decision_date,
        judges=judges,
        counsel=counsel,
        solicitors=solicitors,
        subjects=subjects,
        keywords=keywords,
        party_full=party_full,
        also_known_as=tuple(aka),
        is_eu=is_eu,
    )


def court_from_label(label: str | None, neutral: str | None = None) -> str | None:
    """Best-effort canonical court code: the neutral citation's court prefix when there
    is one (authoritative), else a match on the descriptive court label."""
    if neutral:
        nm = _NEUTRAL.search(neutral)
        if nm:
            return nm.group(2).lower()
    return _court_code(label)


def westlaw_identity(parsed: ParsedWestlaw) -> tuple[str, str]:
    """The stable_id a Westlaw case is keyed by, and the kind of identity it is:

      * ``neutral`` — a neutral citation → its Find Case Law slug (``ukpc/2005/37``),
        so it merges with the same case held from BAILII/FCL;
      * ``ecli`` — an EU case reported in UK series → ``ECLI:EU:C:2016:198``, the key
        CELLAR already uses, so a Westlaw EU export merges rather than duplicating;
      * ``wl`` — otherwise a surrogate from the Westlaw document id
        (``westlaw:1999-wl-250101``); the parallel report citations still resolve to it
        as aliases;
      * ``report`` — a pre-neutral law report with **no** Westlaw id in its header (the
        header citation *is* the report, e.g. "[1982] 1 W.L.R. 149") → a surrogate slugged
        from that preferred report citation (``westlaw:1982-1-w-l-r-149``). Stable across
        re-downloads and dedup-friendly, unlike a content hash;
      * ``hash`` — last resort for a citation-less export: a content-hash surrogate.

    The importer additionally checks whether any report-citation alias already resolves
    to a held document before minting a fresh surrogate — that's where a pre-neutral
    case matches its BAILII copy.
    """
    from ..citations import extract_citations

    if parsed.neutral_citation:
        cites = [c for c in extract_citations(parsed.neutral_citation)
                 if c.candidate_id and c.method == "neutral_citation"]
        if cites:
            return cites[0].candidate_id, "neutral"
    if parsed.ecli:
        return parsed.ecli, "ecli"
    if parsed.wl_number:
        return "westlaw:" + parsed.wl_number.lower().replace(" ", "-"), "wl"
    # a preferred report citation → a stable, meaningful surrogate (a re-download of the
    # same report keys the same id, so it dedupes; an opaque hash would not).
    for c in parsed.report_citations:
        if _WLUK.search(c) or _WL_NUMBER.search(c):
            continue  # Westlaw's own pseudo-citations aren't a durable public identity
        slug = re.sub(r"[^a-z0-9]+", "-", c.lower()).strip("-")
        if slug:
            return "westlaw:" + slug, "report"
    # last resort: a content hash surrogate (a citation-less export)
    from ..core.models import sha256_bytes
    return "westlaw:" + sha256_bytes(parsed.text.encode("utf-8"))[:16], "hash"
